In [1]:
import numpy as np

## DataTypes and Attributes 

In [2]:
#numpy has only one main datatype and its ndarray
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr2 = np.array([[1.0,2,3],[4,5,6]])

In [5]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
arr2.shape # gives rows,column of array

(2, 3)

In [7]:
arr.dtype,arr2.dtype

(dtype('int32'), dtype('float64'))

In [8]:
arr.size,arr2.size #gives total number of elemenrs in the array

(3, 6)

In [9]:
#Create a DataFrame using numpy array
import pandas as pd
df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## Creating arrays

In [10]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [11]:
a1.dtype

dtype('int32')

In [12]:
one = np.ones((2,3)) #gives array of 1 and datatype is float 
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
one_2 = np.ones((3,3),int)
one_2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
one_2.dtype

dtype('int32')

In [15]:
zeros = np.zeros((2,3),int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
range_array= np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [17]:
random_array = np.random.randint(0,10,size = (3,4)) 
random_array

array([[8, 4, 4, 2],
       [8, 5, 8, 8],
       [0, 2, 2, 0]])

In [18]:
random_array_2 = np.random.random((5,2)) #gives random float b/w 0,1 and size needs to be defined
random_array_2

array([[0.68273588, 0.46954305],
       [0.38169017, 0.7129651 ],
       [0.23849509, 0.67587368],
       [0.56443268, 0.96833338],
       [0.17372364, 0.48842038]])

In [19]:
random_array_3 = np.random.rand(*(3,4)) #works same like random.random
random_array_3

array([[0.95229295, 0.04093108, 0.83945371, 0.7419926 ],
       [0.18018169, 0.97418562, 0.06594529, 0.48144841],
       [0.83434264, 0.79618167, 0.79863246, 0.26073291]])

In [20]:
# Pseudo-random number
np.random.seed(1) #keeps the numbers same in the same block when random is used
rand_array_4 = np.random.randint(10,size = (3,4))# this will not change everytime its executed
rand_array_4

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [21]:
rand_array_4 = np.random.randint(10,size = (3,4)) # this will change everytime its executed
rand_array_4 

array([[5, 2, 4, 2],
       [4, 7, 7, 9],
       [1, 7, 0, 6]])

## Viewing arrays and matrices

In [22]:
np.unique(rand_array_4) # finds the unique element in the array

array([0, 1, 2, 4, 5, 6, 7, 9])

In [23]:
arr


array([1, 2, 3])

In [24]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr[0]

1

In [26]:
arr2[0]

array([1., 2., 3.])

In [27]:
arr2[0,0]

1.0

In [28]:
arr[0:3]

array([1, 2, 3])

In [29]:
arr2[0][0:]

array([1., 2., 3.])

In [30]:
arr2[:,0]

array([1., 4.])

## Manipulating and Comparing arrays

### Arithmetic

In [31]:
arr

array([1, 2, 3])

In [32]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [33]:
arr+ones

array([2., 3., 4.])

In [34]:
arr - ones

array([0., 1., 2.])

In [35]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr2+arr

array([[2., 4., 6.],
       [5., 7., 9.]])

In [37]:
arr2*arr

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [38]:
arr2/arr

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [39]:
arr2**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
np.square(arr2)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
np.add(arr,ones)

array([2., 3., 4.])

In [42]:
arr%2

array([1, 0, 1], dtype=int32)

In [43]:
np.mod(arr,2)

array([1, 0, 1], dtype=int32)

In [44]:
np.exp(arr) #e raised to the power of the value in the array

array([ 2.71828183,  7.3890561 , 20.08553692])

In [45]:
np.log(arr) #log of the value in that array|

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [46]:
listy_list = [1,2,3] #python list

In [47]:
sum(listy_list) #python sum method

6

In [48]:
arr

array([1, 2, 3])

In [49]:
sum(arr)

6

In [50]:
np.sum(arr)

6

Here both sum and np.sum do the same thing on array but we should always use python functions on python datatype and array functions on array

In [51]:
# Creating a massive array
massive_array = np.random.random(1000)

In [52]:
massive_array.size

1000

In [53]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

95.7 μs ± 7.4 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.37 μs ± 50.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [54]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
np.mean(arr2)

3.5

In [56]:
np.mean(massive_array)

0.5015292593849394

In [57]:
np.max(arr2)

6.0

In [58]:
np.min(arr2)

1.0

In [59]:
np.std(arr2)

1.707825127659933

In [60]:
np.var(arr2)

2.9166666666666665

## Reshaping and Transposing

In [61]:
arr3 = np.ones((2,3,4))
arr3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [62]:
arr2*arr3 # here we see broadcast issue so to fix this we see the documentary

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,4) 

In [63]:
arr2_reshaped = arr2.reshape(2,3,1) # sol is to reshape and keep one dimenstion to 1

In [64]:
arr2_reshaped

array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]])

In [65]:
arr2_reshaped*arr3

array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]]])

In [66]:
#transpose
arr2.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [67]:
arr3.T

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## Dot Product

In [68]:
arr2.dot(arr3) #basically matrix multiplication

array([[[ 6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.]],

       [[15., 15., 15., 15.],
        [15., 15., 15., 15.]]])

## Peanut butter store(Dot pro example)

In [69]:
sales = np.array([[10,3,4],[11,11,33],[8,6,99,],[0,9,8],[10,11,11],[11,22,33],[11,9,22]])
sales.shape

(7, 3)

In [70]:
product_daily = pd.DataFrame(sales,index = ["Mon","Tues","wed","thurs","fri","sat","sun"],columns = ["almond","Peanut","Cashews"])
product_daily

almond  Peanut  Cashews
Mon        10       3        4
Tues       11      11       33
wed         8       6       99
thurs       0       9        8
fri        10      11       11
sat        11      22       33
sun        11       9       22

In [71]:
price = np.array([11,22,33])
price.shape

(3,)

In [72]:
price_daily = pd.DataFrame(price.reshape(1,3),index=["Price"],columns=["almond","Peanut","Cashews"])
price_daily

almond  Peanut  Cashews
Price      11      22       33

In [73]:
daily_sales = np.array(sales.dot(price))
daily_sales

array([ 308, 1452, 3487,  462,  715, 1694, 1045])

In [74]:
product_daily ["Total $"] = daily_sales.T

In [75]:
product_daily

almond  Peanut  Cashews  Total $
Mon        10       3        4      308
Tues       11      11       33     1452
wed         8       6       99     3487
thurs       0       9        8      462
fri        10      11       11      715
sat        11      22       33     1694
sun        11       9       22     1045

### Comparision operators 

In [76]:
arr > arr2

array([[False, False, False],
       [False, False, False]])

In [77]:
bool_array = arr >= arr2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [78]:
type(bool_array)

numpy.ndarray

In [79]:
arr>5

array([False, False, False])

In [80]:
arr<5

array([ True,  True,  True])

In [81]:
arr == arr2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting arrays

In [82]:
rando = np.random.randint(10,size = (3,5))
rando

array([[8, 0, 0, 6, 6],
       [8, 9, 3, 9, 7],
       [1, 0, 3, 1, 9]])

In [83]:
np.sort(rando)

array([[0, 0, 6, 6, 8],
       [3, 7, 8, 9, 9],
       [0, 1, 1, 3, 9]])

In [84]:
np.argsort(rando) # instead of sorting they just give the order in ascending order

array([[1, 2, 3, 4, 0],
       [2, 4, 0, 1, 3],
       [1, 0, 3, 2, 4]], dtype=int64)

In [87]:
np.argmin(rando ,axis =1) #index of min number

array([1, 2, 1], dtype=int64)

In [88]:
np.argmin(rando ,axis =0) #index of min number

array([2, 0, 0, 2, 0], dtype=int64)

In [90]:
np.argmax(rando ,axis =1) #index of min number

array([0, 1, 4], dtype=int64)

In [91]:
np.argmin(rando ,axis =0) #index of min number

array([2, 0, 0, 2, 0], dtype=int64)

## Numpy in action

In [103]:
# turn an image in a numpy array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [104]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [105]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)